version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/media:/app/media
      - ./app/generated:/app/generated
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - MANIM_QUALITY=-ql

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
